
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cicd-db?createDatabaseIfNotExist=true
    username: user
    password: user
  application:
    name: spring-cicd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

